/* eslint-disable @next/next/no-img-element */
import Head from 'next/head'
import client from '@/apollo/apollo-client'
import { gql } from '@apollo/client'


export default function Home({ characters }: any) {
  console.log(characters.results);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='m-8'>
        <header className='mb-8'>
          <h1 className="text-3xl font-bold underline">
            Header
          </h1>
        </header>
        <div className='grid gap-6 grid-cols-4'>
          {characters.results.map((char: any) => (
            <div key={char.id}>
              <img src={char.image} alt={char.name} />
              <div>{"Name:"} {char.name} </div>
              <div> {char.gender} </div>
              <div> {char.status} </div>
            </div>
          ))}
        </div>
      </main>
    </>
  )
}


export async function getServerSideProps() {

  const { data } = await client.query({
    query: gql`
      query Characters {
        characters {
          results {
            id
            name
            gender
            status
            image
          }
        }
      }
    `,
  });

  return {
    props: {
      characters: data.characters
    }
  }
};
